# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\65904\Desktop\Train_VIT\cam_record\demo_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1820, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clear_message_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.clear_message_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.clear_message_btn.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(False)
        self.clear_message_btn.setFont(font)
        self.clear_message_btn.setDefault(False)
        self.clear_message_btn.setFlat(False)
        self.clear_message_btn.setObjectName("clear_message_btn")
        self.horizontalLayout.addWidget(self.clear_message_btn)
        self.message_box = QtWidgets.QTextEdit(self.groupBox_2)
        self.message_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.message_box.setFont(font)
        self.message_box.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.message_box.setFrameShape(QtWidgets.QFrame.Box)
        self.message_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.message_box.setUndoRedoEnabled(False)
        self.message_box.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.message_box.setLineWrapColumnOrWidth(0)
        self.message_box.setReadOnly(True)
        self.message_box.setObjectName("message_box")
        self.horizontalLayout.addWidget(self.message_box)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.op_tab = QtWidgets.QTabWidget(self.widget)
        self.op_tab.setMinimumSize(QtCore.QSize(0, 0))
        self.op_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.op_tab.setFont(font)
        self.op_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.op_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.op_tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.op_tab.setObjectName("op_tab")
        self.camera_tab = QtWidgets.QWidget()
        self.camera_tab.setObjectName("camera_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.camera_tab)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.op_tab.addTab(self.camera_tab, "")
        self.pose2d_tab = QtWidgets.QWidget()
        self.pose2d_tab.setObjectName("pose2d_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pose2d_tab)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.op_tab.addTab(self.pose2d_tab, "")
        self.pose3d_tab = QtWidgets.QWidget()
        self.pose3d_tab.setObjectName("pose3d_tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.pose3d_tab)
        self.horizontalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.op_tab.addTab(self.pose3d_tab, "")
        self.verticalLayout_8.addWidget(self.op_tab)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.op_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "操作訊息"))
        self.clear_message_btn.setText(_translate("MainWindow", "清除\n"
"Log"))
        self.message_box.setDocumentTitle(_translate("MainWindow", "訊息"))
        self.message_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><title>訊息</title><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微軟正黑體\',\'微軟正黑體\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.op_tab.setTabText(self.op_tab.indexOf(self.camera_tab), _translate("MainWindow", "攝影機"))
        self.op_tab.setTabText(self.op_tab.indexOf(self.pose2d_tab), _translate("MainWindow", "2D偵測"))
        self.op_tab.setTabText(self.op_tab.indexOf(self.pose3d_tab), _translate("MainWindow", "3D偵測"))
