# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\65904\Desktop\Train_VIT\cam_record\src\Original\adjust\adjust.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(636, 69)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.kpt_z = QtWidgets.QSpinBox(Form)
        self.kpt_z.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kpt_z.setFont(font)
        self.kpt_z.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.kpt_z.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.kpt_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kpt_z.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.kpt_z.setMaximum(10000)
        self.kpt_z.setProperty("value", 0)
        self.kpt_z.setObjectName("kpt_z")
        self.gridLayout.addWidget(self.kpt_z, 0, 3, 1, 1)
        self.kpt_btn = QtWidgets.QRadioButton(Form)
        self.kpt_btn.setObjectName("kpt_btn")
        self.gridLayout.addWidget(self.kpt_btn, 0, 0, 1, 1)
        self.kpt_x = QtWidgets.QSpinBox(Form)
        self.kpt_x.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kpt_x.setFont(font)
        self.kpt_x.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.kpt_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kpt_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.kpt_x.setMinimum(-2000)
        self.kpt_x.setMaximum(3000)
        self.kpt_x.setProperty("value", 0)
        self.kpt_x.setObjectName("kpt_x")
        self.gridLayout.addWidget(self.kpt_x, 0, 1, 1, 1)
        self.kpt_y = QtWidgets.QSpinBox(Form)
        self.kpt_y.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kpt_y.setFont(font)
        self.kpt_y.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.kpt_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kpt_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.kpt_y.setMinimum(-2000)
        self.kpt_y.setMaximum(3000)
        self.kpt_y.setProperty("value", 0)
        self.kpt_y.setObjectName("kpt_y")
        self.gridLayout.addWidget(self.kpt_y, 0, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.kpt_btn.setText(_translate("Form", "RKnee"))
